### PR TITLE
Authenticate LMI request with HMAC header

### PR DESCRIPTION
**Pull request by lukasz-kaniowski**
- regenrate vcr cassettes
- use rails secrets to configure lmi keys

### CODE REVIEW

**Comment by lukasz-kaniowski** [comment]
I'm working on adding tests for this

**Comment by nathancashmoredwp** [comment]
roger that.

**Comment by nathancashmoredwp** [comment]
Hmmmm ... deployed version does not look good.

**Comment by lukasz-kaniowski** [comment]
fixed now

**Comment by nathancashmoredwp** [comment]
👍 🎉

**Pull request merged**
